language: node_js
node_js:
  - 6
script:
  - echo 'Hello Firebase'
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}
notifications:
  email: false
