language: node_js
node_js:
  - 6
script:
  - yarn run build:remote
install:
  - yarn install
  - yarn global add firebase-tools
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}
notifications:
  email: false
